version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8007:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_SERVER=db
      - MYSQL_DB=${MYSQL_DATABASE}
    restart: unless-stopped

    command: sh -c "sleep 20 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
